### ISSUE TITLE
`"configuration"(dependency)` notation is unsupported

### ISSUE THREAD

**Issue by ZacSweers** [square/gradle-dependencies-sorter#113]
Currently a dependencies block like below in kotlin-dsl will failure to parse

```kotlin
dependencies {
  "testFixturesApi"(projects.libraries.foundation.coroutines.test)
}
```

This is with 0.7 though so it's possible it's fixed in 0.8. Will try to confirm

**Comment by autonomousapps** [comment]
@ZacSweers have you tested with 0.8?

**Comment by ZacSweers** [comment]
No because I'm unable to update to it due to #110 :/

**Comment by ZacSweers** [comment]
No because I'm unable to update to it due to #110 :/

**Comment by autonomousapps** [comment]
Linked PR validates that we currently support this with improved test coverage.
