### ISSUE TITLE
versions.toml support

### ISSUE THREAD

**Issue by WhosNickDoglio** [square/gradle-dependencies-sorter#19]
Now that Version Catalogs are becoming more popular it would be great if this project could also sort the TOML files

**Comment by ZacSweers** [comment]
This should really be titled "versions.toml` support maybe?

**Comment by yschimke** [comment]
Now that Android Studio has opinions on version catalog naming, renaming entries also, would be a good thing for consistency.

**Comment by ZacSweers** [comment]
At some point I think this becomes a separate tool and I think this is more or less at that boundary

**Comment by ZacSweers** [comment]
Going to make a call that this is out of scope for this tool

**Comment by pemistahl** [comment]
Hi, this is to let you know that I've just released a new Gradle plugin that allows to check and format version catalog TOML files.

https://github.com/pemistahl/version-catalog-linter-gradle-plugin

Please try it if you are interested and open an issue if you have ideas for improvements. Thanks!
