### ISSUE TITLE
Task 'sortDependencies' not found in project

### ISSUE THREAD

**Issue by ivanalvarado** [square/gradle-dependencies-sorter#20]
I've applied the gradle plugin to my project by adding the following to my top-level build.gradle:
```groovy
plugins {
    id("com.squareup.sort-dependencies") version "0.1"
}
```
and the project syncs successfully. I've verified my project is finding the artifact successfully by changing the version and observing a failure during the sync.

However, when I run
```
$ ./gradlew :app:sortDependencies
```

I get the following error:
```
* What went wrong:
Task 'sortDependencies' not found in project ':app'.
```

Then, I run 
```
$ ./gradlew :app:tasks
```
to verify the tasks available and `sortDependencies` is not listed.

Any ideas what might be going on here or how I can troubleshoot this? Thanks!

**Comment by ivanalvarado** [comment]
Ok, it works if I apply the plugin at the module level, i.e. `:app/build.gradle`

**Comment by ivanalvarado** [comment]
Now, I'm running into https://github.com/square/gradle-dependencies-sorter/issues/17 but the workaround doesn't work for me. Just going to use the CLI method for now.

**Comment by autonomousapps** [comment]
The plugin does have to be applied at the project level, not in the root project. I'm going to close this and take a look at #17. Feel free to reopen if something is unclear.
