### ISSUE TITLE
Do not fail on modules with no build script

### ISSUE THREAD

**Issue by JakeWharton** [square/gradle-dependencies-sorter#79]
Right now it fails with `NoSuchFileException`, but I think it would better to silently no-op. This would allow applying to all subprojects without having to worry about the intermediate projects that Gradle creates when nesting two-levels (or more) deep.

**Comment by autonomousapps** [comment]
Are you doing something like this?
```
// root build.gradle
subprojects {
  apply plugin: "com.squareup.sort-dependencies"
}
```

**Comment by JakeWharton** [comment]
Yeah basically same effect. I have a settings plugin that applies a build plugin to all projects which was unconditionally applying this plugin.
