### ISSUE TITLE
The suggestion to fixed non-sorted dependencies is wrong

### ISSUE THREAD

**Issue by oldergod** [square/gradle-dependencies-sorter#89]
https://github.com/square/gradle-dependencies-sorter/blob/6f781ee939a199e3f83ff76b1cc054d96979c8e5/app/src/main/kotlin/com/squareup/sort/SortCommand.kt#L204-L217

It should say `./gradlew sortDependencies`

**Comment by autonomousapps** [comment]
Thanks for the issue. Fair point -- I think the command needs to be made context-aware. It should either suggest running the CLI directly or the gradle task, depending on how it was invoked.
